# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

AWS_ACCESS_KEY_ID: "AKIAIT5FQEFTQHKHYV4A"
AWS_SECRET_ACCESS_KEY: "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"

development:
  AWS_BUCKET: crankplan-d
production:
  AWS_BUCKET: crankplan-p