# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

AWS_ACCESS_KEY_ID: "AKIAIHQWYIHUDNPTRMIA"
AWS_SECRET_ACCESS_KEY: "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"
GMAIL_DOMAIN: gmail.com
GMAIL_USERNAME: hecontreraso
GMAIL_PASSWORD: wncfllkdkqyepmkh

development:
  AWS_BUCKET: crankplan-d
production:
  AWS_BUCKET: crankplan-p

